import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "../provider";
import { AppbarMerchant } from "../components/AppbarMerchant";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "QuickPay",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className="bg-[#ebe6e6]">
      <Providers>
        <body className={inter.className}>
          <div className="min-w-screen min-h-screen bg-[#ebe6e6]">
            <AppbarMerchant />
            {children}
          </div>
        </body>
      </Providers>
    </html>
  );
}
